### PR TITLE
[Do not merge until Git dependencies removed] Uncompressed Encoding for Affine Points

### PR DESCRIPTION
**Pull request by winston-h-zhang**
This PR implements a feature (`uncompressed_serde`) that optimizes the speed of serializing public parameters by using an uncompressed encoding that removes the overhead of computing the second coordinate of points. Note: this PR depends on PRs in `pasta_curves` and `neptune`, here: https://github.com/zcash/pasta_curves/pull/73 and https://github.com/lurk-lab/neptune/pull/192. For now, we point at branches on `lurk-lab` maintained forks.

I compared the performance on the `minroot` public parameters. Based on some eyeballing benchmarks run on my local machine, deserialization time reduces from 2.7s to 100ms. Downstream in [`lurk-rs`](https://github.com/lurk-lab/lurk-rs), where the circuit is much bigger -- and `serde` has become a significant time factor in initializing proving times -- deserialization time on the [`sha256`](https://github.com/lurk-lab/lurk-rs/blob/master/examples/sha256.rs) example reduces from 120s to 7s. Note, the uncompressed encoding for pasta points are `[u8; 64]`, so this does have the downside of eating twice as much memory compared to the normal/compressed encoding.

The significant improvement in deserialization time makes caching public parameters viable. This would short circuit the need to regenerate costly public parameters each run, improving the develop/iterate experience. This infrastructure currently exists in `lurk-rs`, and this PR mainly wants to improve its efficiency. Although hopefully, this clarifies a growing need for systematic approach to deal with public parameters in Nova, and leaves future work open to discussion.

As for the feature itself, it is implemented via the [`UncompressedEncoding`](https://docs.rs/group/0.13.0/group/trait.UncompressedEncoding.html) trait in `group`. We only apply the uncompressed serde to `CommitmentKey`, since the structure stores 90% of the data.

### CODE REVIEW

**Review by huitseeker — APPROVED** [review]
> [on MinRoot] deserialization time reduces from 2.7s to 100ms. Downstream in lurk-rs, where the circuit is much bigger [...] deserialization time on the sha256 benchmark reduces from 120s to 7s.

Nice work!

**Comment by winston-h-zhang** [comment]
@microsoft-github-policy-service agree [company="lurk-lab"]

**Comment by winston-h-zhang** [comment]
@microsoft-github-policy-service agree company="Lurk Lab"

**Comment by CPerezz** [comment]
This will probably be superset by #198 

Also, if we plan to move to `halo2curves` we already provide this functionallity in our `SerdeObject` trait. See: https://github.com/privacy-scaling-explorations/halo2curves/blob/main/src/serde.rs

**Comment by srinathsetty** [comment]
Hi @winston-h-zhang is this PR still being worked on? I've heard interest in this from several others.

**Comment by srinathsetty** [comment]
Hi @CPerezz 

> This will probably be superset by #198
> 
> Also, if we plan to move to `halo2curves` we already provide this functionallity in our `SerdeObject` trait. See: https://github.com/privacy-scaling-explorations/halo2curves/blob/main/src/serde.rs

What is the best way to use SerdeObject trait to get fast deserialization of field elements? Are there examples of this somewhere to compose this automatically with serde's methods?

**Comment by huitseeker** [comment]
@srinathsetty some answers to these questions might reside in https://github.com/privacy-scaling-explorations/halo2curves/pull/39

**Comment by srinathsetty** [comment]
It seems like this may be a stale PR. Please reopen this if we want to pursue it.

**Pull request closed without merging**
