### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by xiaolou86**
fix some typos

### CODE REVIEW

**Comment by srinathsetty** [comment]
Hi, @xiaolou86, thanks for the PR! Could you please sign the CLA so this can be merged?

**Comment by xiaolou86** [comment]
@microsoft-github-policy-service agree

**Comment by xiaolou86** [comment]
@srinathsetty Thank you for your review, and how to sign the CLA?

**Comment by srinathsetty** [comment]
I'm not sure why the bot is not getting activated to ask you to sign the CLA.

**Comment by xiaolou86** [comment]
@srinathsetty I resolved conflicts and pushed again. Now CLA is passed! Thanks for your review.

**Pull request merged**
