### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by 3for**
Fix some comment typo.

### CODE REVIEW

**Comment by srinathsetty** [comment]
Thanks @3for! Could you please reply to the CLA bot?

**Comment by 3for** [comment]
I have sole ownership of intellectual property rights to my Submissions
and I am not making Submissions in the course of work for my employer.

Srinath Setty ***@***.***> 于2023年7月7日周五 00:58写道：

**Comment by srinathsetty** [comment]
Hi @3for, the message needs to be what is specified in the bot message.

> @microsoft-github-policy-service agree

**Comment by 3for** [comment]
@microsoft-github-policy-service agree



Srinath Setty ***@***.***> 于2023年7月7日周五 10:50写道：

**Pull request merged**
